<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\HB.Infrastructure.Redis.Shared\HB.Infrastructure.Redis.Shared.projitems" Label="Shared" />

	<Import Project="..\..\common.props" />


	<ItemGroup>
		<PackageReference Include="Polly" Version="8.5.2" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.31" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HB.FullStack.KVStore\HB.FullStack.KVStore.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
	</ItemGroup>

</Project>
