
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1813:Avoid unsealed attributes", Justification = "<Pending>", Scope = "type", Target = "~T:HB.Framework.Database.Entity.DatabaseEntityPropertyAttribute")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1717:Only FlagsAttribute enums should have plural names", Justification = "<Pending>", Scope = "type", Target = "~T:HB.Framework.Database.DatabaseResultStatus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1717:Only FlagsAttribute enums should have plural names", Justification = "<Pending>", Scope = "type", Target = "~T:HB.Framework.Database.DbTransactionStatus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.Where`1.And(System.Linq.Expressions.Expression{System.Func{`0,System.Boolean}})~HB.Framework.Database.SQL.Where`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.Where`1.And``1(System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}})~HB.Framework.Database.SQL.Where`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.Where`1.And``2(System.Linq.Expressions.Expression{System.Func{``0,``1,System.Boolean}})~HB.Framework.Database.SQL.Where`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.Where`1.Or``1(System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}})~HB.Framework.Database.SQL.Where`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.Where`1.Or``2(System.Linq.Expressions.Expression{System.Func{``0,``1,System.Boolean}})~HB.Framework.Database.SQL.Where`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.Where`1.Or(System.Linq.Expressions.Expression{System.Func{`0,System.Boolean}})~HB.Framework.Database.SQL.Where`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.WhereExpression`1.And(System.Linq.Expressions.Expression{System.Func{`0,System.Boolean}})~HB.Framework.Database.SQL.WhereExpression`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.WhereExpression`1.Or(System.Linq.Expressions.Expression{System.Func{`0,System.Boolean}})~HB.Framework.Database.SQL.WhereExpression`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.WhereExpression`1.And``1(System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}})~HB.Framework.Database.SQL.WhereExpression`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.WhereExpression`1.And``2(System.Linq.Expressions.Expression{System.Func{``0,``1,System.Boolean}})~HB.Framework.Database.SQL.WhereExpression`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.WhereExpression`1.Or``1(System.Linq.Expressions.Expression{System.Func{``0,System.Boolean}})~HB.Framework.Database.SQL.WhereExpression`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "<Pending>", Scope = "member", Target = "~M:HB.Framework.Database.SQL.WhereExpression`1.Or``2(System.Linq.Expressions.Expression{System.Func{``0,``1,System.Boolean}})~HB.Framework.Database.SQL.WhereExpression`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1717:Only FlagsAttribute enums should have plural names", Justification = "<Pending>", Scope = "type", Target = "~T:HB.Framework.Database.Transaction.DatabaseTransactionStatus")]

