<Project>

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<Nullable>enable</Nullable>
		<!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />-->
		<AnalysisMode>All</AnalysisMode>

		<!--<AnalysisMode>AllEnabledByDefault</AnalysisMode>-->
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>
	
	<PropertyGroup>
		<VersionSuffix>$(VersionSuffix)</VersionSuffix>
		<Version>9.0.0</Version>
		<Version Condition=" '$(VersionSuffix)' != '' ">$(Version)-$(VersionSuffix)</Version>
		<Product>HB.FullStack</Product>
		<Authors>yzbai@brlite.com</Authors>
		<Company>Wuxi Brilliant Technology Company Limited.</Company>
		<Copyright>@2017 Wuxi Brilliant Technology Company Limited. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/yzbai/HB.FullStack</PackageProjectUrl>
		<RepositoryUrl>https://github.com/yzbai/HB.FullStack</RepositoryUrl>

		<!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>

		<EmbedAllSources>true</EmbedAllSources>
		<!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
		<EmbedUntrackedSources>true</EmbedUntrackedSources>

		<!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		
	</PropertyGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.1" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" />

	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All"/>
	</ItemGroup>
</Project>
