//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HB.Framework.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HB.Framework.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the collection is null or has null item in it..
        /// </summary>
        internal static string CollectionAnyNullErrorMessage {
            get {
                return ResourceManager.GetString("CollectionAnyNullErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the collection is null or emtpy.
        /// </summary>
        internal static string CollectionNullOrEmptyErrorMessage {
            get {
                return ResourceManager.GetString("CollectionNullOrEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the dictionary is null or empty.
        /// </summary>
        internal static string DictionaryNullOrEmptyErrorMessage {
            get {
                return ResourceManager.GetString("DictionaryNullOrEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        internal static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string is not a valid email string.
        /// </summary>
        internal static string NotEmailErrorMessage {
            get {
                return ResourceManager.GetString("NotEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string is not a valid loginName string.
        /// </summary>
        internal static string NotLoginNameErrorMessage {
            get {
                return ResourceManager.GetString("NotLoginNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string is not a valid mobile number string.
        /// </summary>
        internal static string NotMobileErrorMessage {
            get {
                return ResourceManager.GetString("NotMobileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string is not a valid passoword string.
        /// </summary>
        internal static string NotPasswordErrorMessage {
            get {
                return ResourceManager.GetString("NotPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameter is null or empty.
        /// </summary>
        internal static string ParameterNullOrEmptyErrorMessage {
            get {
                return ResourceManager.GetString("ParameterNullOrEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string can not be empty..
        /// </summary>
        internal static string StringCanNotBeEmpty {
            get {
                return ResourceManager.GetString("StringCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two string is not equal..
        /// </summary>
        internal static string StringNotEqualErrorMessage {
            get {
                return ResourceManager.GetString("StringNotEqualErrorMessage", resourceCulture);
            }
        }
    }
}
