<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>

		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		
		<!--This is against common.props-->
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="EmbeddedResources\PropertyTrackableObject.cs" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="EmbeddedResources\PropertyTrackableObject.cs">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />

		
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.Bcl.AsyncInterfaces" Version="9.0.3" />
	  <PackageReference Update="Microsoft.Bcl.HashCode" Version="6.0.0" />
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
	</ItemGroup>

</Project>
