//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HB.FullStack.Database.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HB.FullStack.Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DatabaseName not found in SystemInfo Table..
        /// </summary>
        internal static string DatabaseNameNotFoundInSystemInfoTable
        {
            get
            {
                return ResourceManager.GetString("DatabaseNameNotFoundInSystemInfoTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to version should greater than 1..
        /// </summary>
        internal static string MigrateOldVersionErrorMessage
        {
            get
            {
                return ResourceManager.GetString("MigrateOldVersionErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to you can only take 1 step further each time..
        /// </summary>
        internal static string MigrateVersionStepErrorMessage
        {
            get
            {
                return ResourceManager.GetString("MigrateVersionStepErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to oldVersion should always lower than newVersions in Database Migrations..
        /// </summary>
        internal static string MigrationVersionErrorMessage
        {
            get
            {
                return ResourceManager.GetString("MigrationVersionErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DO NOT MIX JOIN UP..
        /// </summary>
        internal static string SqlJoinTypeMixedErrorMessage
        {
            get
            {
                return ResourceManager.GetString("SqlJoinTypeMixedErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to use a already finished transactioncontenxt..
        /// </summary>
        internal static string TransactionAlreadyFinishedMessage
        {
            get
            {
                return ResourceManager.GetString("TransactionAlreadyFinishedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type not valid..
        /// </summary>
        internal static string TypeNotValidErrorMessage
        {
            get
            {
                return ResourceManager.GetString("TypeNotValidErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version not found in SystemInfo Table..
        /// </summary>
        internal static string VersionNotFoundInSystemInfoTable
        {
            get
            {
                return ResourceManager.GetString("VersionNotFoundInSystemInfoTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Database Version should greater than 0..
        /// </summary>
        internal static string VersionShouldBePositiveMessage
        {
            get
            {
                return ResourceManager.GetString("VersionShouldBePositiveMessage", resourceCulture);
            }
        }
    }
}
