<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />


	<ItemGroup>
	  <ProjectReference Include="..\HB.FullStack.Common\HB.FullStack.Common.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
	</ItemGroup>

</Project>
