<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\..\common.maui.props" />
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>Todo.Client.MobileApp</RootNamespace>
		<!-- Display name -->
		<ApplicationTitle>Todo.Client.MobileApp</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.todo.client.mobileapp</ApplicationId>
		<ApplicationIdGuid>e4ccb755-385f-468d-80a3-a7aede8db0ae</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="appsettings.Development.json" />
		<None Remove="appsettings.json" />
		<None Remove="appsettings.Production.json" />
		<None Remove="ConstantSettings.Debug.json" />
		<None Remove="ConstantSettings.Release.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.Development.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.Production.json" />
		<EmbeddedResource Include="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="5.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.Markup" Version="3.1.0" />
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="1.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\src\HB.FullStack.Client.MauiLib\HB.FullStack.Client.MauiLib.csproj" />
		<ProjectReference Include="..\..\..\src\HB.FullStack.Common.SourceGenerators\HB.FullStack.Common.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\Todo.Shared\Todo.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Models\" />
		<Folder Include="Repos\" />
		<Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Pages\HomePage.xaml.cs">
			<DependentUpon>HomePage.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
