<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.test.props" />

 

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.3" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.8.3" />
		<PackageReference Include="MSTest.TestFramework" Version="3.8.3" />
		<PackageReference Include="coverlet.collector" Version="6.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\HB.Infrastructure.IdGen\HB.Infrastructure.IdGen.csproj" />
		<ProjectReference Include="..\..\src\HB.Infrastructure.Redis.Cache\HB.Infrastructure.Redis.Cache.csproj" />
		<ProjectReference Include="..\..\src\HB.Infrastructure.SQLite\HB.Infrastructure.SQLite.csproj" />
		<ProjectReference Include="..\HB.FullStack.BaseTest\HB.FullStack.BaseTest.csproj" />
	</ItemGroup>

</Project>
