<Project Sdk="MSTest.Sdk/3.6.4">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HB.FullStack.Utils\HB.FullStack.Utils.csproj" />
  </ItemGroup>

</Project>
