name: FullStack-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:

    runs-on: windows-latest
    name: Android Build

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.x
    
    - name: Install MAUI Workloads
      run:
        dotnet workload install maui
        
    - name: Restore dependencies
      run: dotnet restore HB.FullStack.sln
    
    - name: Build
      run: dotnet build HB.FullStack.sln --configuration Release --no-restore
